name: CI

on:
  # push:
  #   branches:
  #     - main

  # https://frontside.com/blog/2020-05-26-github-actions-pull_request
  pull_request:
    types: [ opened, edited, synchronize, reopened ]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm i

      - name: Lint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm i

      - name: Typecheck
        run: npm run typecheck
