name: 'Deploy(main)'

on:
  push:
    branches:
      - main

  pull_request:
    types: [ opened, edited, synchronize, reopened ]
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm i

      - run: npm run lint
      - run: npm run typecheck

  deploy:
    needs: check
    name: 'Deploy to vercel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/netlify-deploy
      - name: deploy to netlify
        uses: jsmrcaga/action-netlify-deploy@v1.8.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          use_nvm: false
          build_command: 'npm run build:docs'
          build_directory: 'docs/docs/.vitepress/dist'

      # https://github.com/marketplace/actions/deploy-to-vercel-action
      - name: deploy to vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
